### ISSUE TITLE
Stuck at REACT_APP_API_URL  during setup

### ISSUE THREAD

**Issue by bansaltushar014** [phondani0/e_store#6]
Hi, 

During the setup, I am confused with the URL need to be set in the env file of the client Folder. Which API URL needs to be set?

**Comment by phondani0** [comment]
REACT_APP_API_URL should contain your server URL.

eg: If you are running it at the localhost:3500 your API URL will be:

REACT_APP_API_URL = http://localhost:3500

**Comment by bansaltushar014** [comment]
Okay, Thanks
